development:
  auth0_domain: dev-05kbhpforqlzvh7n.us.auth0.com
  auth0_client_id: prJ0sSCcyJs6o6VaRmm1btEcgdVRA3Zy
  auth0_client_secret: _ZJXPLk0bGFKrU_FsURKWy9r1ZuLtmnKCcmmAVcXTW8Cz1DAanJ0NU0fc51pHJaj